// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tkudlicka/portflux-api/core/models"
)

// BrokerService is an autogenerated mock type for the BrokerService type
type BrokerService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, broker
func (_m *BrokerService) Create(ctx context.Context, broker models.CreateBrokerReq) (models.CreationResp, error) {
	ret := _m.Called(ctx, broker)

	var r0 models.CreationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateBrokerReq) (models.CreationResp, error)); ok {
		return rf(ctx, broker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateBrokerReq) models.CreationResp); ok {
		r0 = rf(ctx, broker)
	} else {
		r0 = ret.Get(0).(models.CreationResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateBrokerReq) error); ok {
		r1 = rf(ctx, broker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMany provides a mock function with given fields: ctx, brokers
func (_m *BrokerService) CreateMany(ctx context.Context, brokers []models.CreateBrokerReq) (models.MultiCreationResp, error) {
	ret := _m.Called(ctx, brokers)

	var r0 models.MultiCreationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.CreateBrokerReq) (models.MultiCreationResp, error)); ok {
		return rf(ctx, brokers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.CreateBrokerReq) models.MultiCreationResp); ok {
		r0 = rf(ctx, brokers)
	} else {
		r0 = ret.Get(0).(models.MultiCreationResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.CreateBrokerReq) error); ok {
		r1 = rf(ctx, brokers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, ID
func (_m *BrokerService) Delete(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *BrokerService) GetAll(ctx context.Context) ([]models.BrokerResp, error) {
	ret := _m.Called(ctx)

	var r0 []models.BrokerResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.BrokerResp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.BrokerResp); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BrokerResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *BrokerService) GetByID(ctx context.Context, ID string) (models.BrokerResp, error) {
	ret := _m.Called(ctx, ID)

	var r0 models.BrokerResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.BrokerResp, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.BrokerResp); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(models.BrokerResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySlug provides a mock function with given fields: ctx, Slug
func (_m *BrokerService) GetBySlug(ctx context.Context, Slug string) (models.BrokerResp, error) {
	ret := _m.Called(ctx, Slug)

	var r0 models.BrokerResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.BrokerResp, error)); ok {
		return rf(ctx, Slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.BrokerResp); ok {
		r0 = rf(ctx, Slug)
	} else {
		r0 = ret.Get(0).(models.BrokerResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, Slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ID, broker
func (_m *BrokerService) Update(ctx context.Context, ID string, broker models.UpdateBrokerReq) error {
	ret := _m.Called(ctx, ID, broker)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdateBrokerReq) error); ok {
		r0 = rf(ctx, ID, broker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBrokerService creates a new instance of BrokerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerService {
	mock := &BrokerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
