// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tkudlicka/portflux-api/core/models"
)

// CryptoCurrencyService is an autogenerated mock type for the CryptoCurrencyService type
type CryptoCurrencyService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cryptoCurrency
func (_m *CryptoCurrencyService) Create(ctx context.Context, cryptoCurrency models.CreateCryptoCurrencyReq) (models.CreationResp, error) {
	ret := _m.Called(ctx, cryptoCurrency)

	var r0 models.CreationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCryptoCurrencyReq) (models.CreationResp, error)); ok {
		return rf(ctx, cryptoCurrency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCryptoCurrencyReq) models.CreationResp); ok {
		r0 = rf(ctx, cryptoCurrency)
	} else {
		r0 = ret.Get(0).(models.CreationResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateCryptoCurrencyReq) error); ok {
		r1 = rf(ctx, cryptoCurrency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMany provides a mock function with given fields: ctx, cryptoCurrency
func (_m *CryptoCurrencyService) CreateMany(ctx context.Context, cryptoCurrency []models.CreateCryptoCurrencyReq) (models.MultiCreationResp, error) {
	ret := _m.Called(ctx, cryptoCurrency)

	var r0 models.MultiCreationResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.CreateCryptoCurrencyReq) (models.MultiCreationResp, error)); ok {
		return rf(ctx, cryptoCurrency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.CreateCryptoCurrencyReq) models.MultiCreationResp); ok {
		r0 = rf(ctx, cryptoCurrency)
	} else {
		r0 = ret.Get(0).(models.MultiCreationResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.CreateCryptoCurrencyReq) error); ok {
		r1 = rf(ctx, cryptoCurrency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, ID
func (_m *CryptoCurrencyService) Delete(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *CryptoCurrencyService) GetAll(ctx context.Context) ([]models.CryptoCurrencyResp, error) {
	ret := _m.Called(ctx)

	var r0 []models.CryptoCurrencyResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.CryptoCurrencyResp, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.CryptoCurrencyResp); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CryptoCurrencyResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *CryptoCurrencyService) GetByID(ctx context.Context, ID string) (models.CryptoCurrencyResp, error) {
	ret := _m.Called(ctx, ID)

	var r0 models.CryptoCurrencyResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.CryptoCurrencyResp, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.CryptoCurrencyResp); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(models.CryptoCurrencyResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ID, cryptoCurrencyModels
func (_m *CryptoCurrencyService) Update(ctx context.Context, ID string, cryptoCurrencyModels models.UpdateCryptoCurrencyReq) error {
	ret := _m.Called(ctx, ID, cryptoCurrencyModels)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdateCryptoCurrencyReq) error); ok {
		r0 = rf(ctx, ID, cryptoCurrencyModels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCryptoCurrencyService creates a new instance of CryptoCurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptoCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptoCurrencyService {
	mock := &CryptoCurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
